const mongoose = require('mongoose')
const Product = require('../models/Product') 
const User = require('../models/User')
const productData = require('./data/productData')
const userData = require('./data/userData')
const { dbURI } = require('../config/enviroment')
mongoose.Promise = require('bluebird')

mongoose.connect(dbURI, { useNewUrlParser: true })
  .then(() => mongoose.connection.db.dropDatabase())
  .then(() => Product.create(productData))
  .then(() => User.create(userData))
  .then(() => console.log('Successfully seeded!'))
  .catch((err) => console.log(err))
  .finally(() => mongoose.connection.close())